[files]
# !! Use '/' for all paths !! '\' will crash the program

# Local VOD folder
# The newest file here will be uploaded
VOD_DIR = ""
# What to do with VODs after uploading
# ""		: leave VODs in place
# "move"	: move VODs to another directory
# "delete"	: remove VODs from local disk (risky)
POST_UPLOAD_STEP = ""
# Folder to archive uploaded VODs to
# Only needed if POST_UPLOAD_STEP = "move"
VOD_ARCHIVE_DIR = ""

[ttv]
# Your TTV username
LOGIN = ""

[upload]
# Valid options: "public", "private", "unlisted"
VISIBILITY = "private"
# Include information about your stream in the description:
# {TITLE}	: stream title
# {DATE}	: date streamed
# {URL}		: original VOD url
DESCRIPTION = """
Streamed on {DATE}
https://twitch.tv/

{URL}
"""
# See https://gist.github.com/dgp/1b24bf2961521bd75d6c
CATEGORY_ID = "20"
# Tags for your video
TAGS = [
	"twitch",
	"vod",
]
# Playlist to add your VODs to
# Leave blank as "" for no playlist
PLAYLIST_ID = ""
