name: Build

on:
  workflow_call:
  push:
    branches-ignore:
    - 'release-v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.19.1"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build server
      run: go build
    
    - name: Build client
      run: |
        cd client
        yarn install
        yarn build

    - name: Zip
      run: |
        Compress-Archive `
        -Path ".credentials", "auto_upload.lua", "config.toml", "auto_upload.exe", "LICENSE" `
        -DestinationPath "auto_upload-${{ github.ref_name }}.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: auto_upload-${{ github.ref_name }}
        path: auto_upload-${{ github.ref_name }}.zip
