name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: auto_upload-${{ github.ref_name }}

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "auto_upload-${{ github.ref_name }}.zip"
        bodyFile: "changelog.md"
        token: ${{ secrets.CI_TOKEN_GH }}
